dist: trusty
sudo: required
language: php
php:
  - 7.2

install: composer install

before_script:
  - git clone https://github.com/krakjoe/pthreads.git
  - cd pthreads
  - phpize
  - ./configure
  - make
  - make install
  - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cd ..
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

script:
  - composer run test

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
#  slack:
#    secure: "lQ1cnbO6rd3gn53EsUk3P3tHRNOAtATyMWgxuS8C00ov7mh4i2fD1beCJqMGmejS8NyOhKGcCLCpN33rKq0CjE+pECY5dJg10PO/p6qf5pmxb8aKTFuyZJDjHHKUfBJ933thrdwhz6pwGznER+Dsd2rSf7x8+PUrCE5mpJC9RYTQC40awqJY+FPBgSQpPa/D9CMSbTfPXE2u5NnN6F3rHCjlP5nAwDf9Z4FzQn9h+O2DoJ9Ct5fMlF+LNLj/fA1UgIjdpUgdjPAMj/F6kaSHQjke7AxjutW6whGWrZ7Db5JNIFukp5ICev7vk2t+CxxRyVvncBCoEs6IQi5q6YFfSPZHk/hd16755QJliN3FuLiOGvfigyvsEIc+FoY/4j7tHPophGV+tT5Ds7hPb8xvh+nH2Gfm2LqEp4o9YaBIv/SmP10/Y/3MC1jtoUKQp15+CgyG2fV0KAnISRiXU5W8TjhhUm6wA2FzkBqkHSl3yYcKU4dpkeNnU4UYBtQvPIBfCoebGHj119kaK2CkwW6XD2eQiBR6HCRWngHNIj/oiYZ24rSYk29cQulMAab2zBHZBuBVyCmIiTB7r8qgtVzT0aI7xyKHM+rWdTmFpQmgr4HgobllB2MZ+h5z7IoeaVVeq62a2ZBe+m0y5X7BnMSf0WLcfTbtePpBBzQDv4nhpIM="
  email:
    recipients:
      - eldar@coralogix.com
    on_success: change
    on_failure: always